<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ProteaseGuru.Tasks</AssemblyName>
    <RootNamespace>ProteaseGuru.Tasks</RootNamespace>
    <ApplicationIcon />
    <StartupObject />
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="mzLib" Version="1.0.585" />
    <PackageReference Include="Nett" Version="0.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\ProteaseGuru.Engine.csproj" />
  </ItemGroup>

</Project>
