<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <ApplicationIcon>Icons\proteaseGuru.ico</ApplicationIcon>
    <AssemblyName>ProteaseGuruGui</AssemblyName>
    <RootNamespace>ProteaseGuruGui</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icons\IconProtein.bmp" />
    <None Remove="Icons\IconRna.bmp" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="mzLib" Version="1.0.585" />
    <PackageReference Include="Nett" Version="0.15.0" />
    <PackageReference Include="OxyPlot.Core" Version="2.2.0" />
    <PackageReference Include="OxyPlot.SkiaSharp" Version="2.2.0" />
    <PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\Engine.csproj" />
    <ProjectReference Include="..\ProteaseGuruGuiFunctions\ProteaseGuruGuiFunctions.csproj" />
    <ProjectReference Include="..\Tasks\Tasks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="ProteaseModificationWindow.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="CustomProteaseWindow.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icons\IconProtein.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IconRna.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="proteaseGuru.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>

    <None Update="Icons\MMnice.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <None Update="Icons\proteaseGuru.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <None Update="Icons\proteaseGuru.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <None Update="Twitter_Logo_Blue.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <None Update="youtube_20.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

  </ItemGroup>

</Project>