<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ProteaseGuruGuiFunctions</AssemblyName>
    <RootNamespace>ProteaseGuruGuiFunctions</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="mzLib" Version="1.0.580" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\Engine.csproj" />
    <ProjectReference Include="..\Tasks\Tasks.csproj" />
  </ItemGroup>

</Project>
